#! /bin/bash

# Keep repository up-to-date with changes

# Install any new git hooks
root=`git rev-parse --show-toplevel`
ln -sf $root/hooks/* $root/.git/hooks/

if [[ -f "$root/update.sh" ]]; then
    bash $root/update.sh > /dev/null &
fi
